services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env  # Carrega o arquivo .env
    environment:
      - PORT=${PORT:-3000}  # Fallback para 3000 se não definido
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/apitest}
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: