services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGO_CONNECTION:${MONGO_CONNECTION}
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: